Bookers2/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  resources :books, only: [:new, :show, :create, :index, :edit, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :show, :index, :update]




  get 'home/about' => 'homes#about', as: 'about'
end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def change
    create_table :books do |t|

      t.string :title
      t.text :body
      t.integer :user_id

      t.timestamps
    end
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

end

Bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

   validates :comment, presence: true

  end

Bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments, dependent: :destroy


         has_one_attached :profile_image

      def get_profile_image(width, height)

      unless profile_image.attached?
          file_path = Rails.root.join('app/assets/images/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
          profile_image.variant(resize_to_limit: [width, height]).processed
      end


    validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction,  length: { maximum: 50}




end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

Bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

   def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
      BookComment.find(params[:id]).destroy
      redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    flash[:notice] = "You have created book successfully."
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new

  end

  def edit
     @book = Book.find(params[:id])
     if @book.user != current_user
       redirect_to books_path
     end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update

    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id)
     flash[:notice] = "You have updated book successfully."
    else
     render :edit
    end

  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

Bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
     if @user != current_user
       redirect_to user_path(current_user)
     end
  end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id)
     flash[:notice] = "You have updated user successfully."
    else
     render :edit
    end
    end

  def index
    @user = current_user
    @users = User.all
    @books = @user.books
    @book = Book.new
  end

   private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/books/edit.html.erb
<main>
    <% if @book.errors.any? %>
  <div id= "error_explanation" >
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

     <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  		<div class="form-group">
    <label for="book_title">Title</label>
    <div><%= f.text_field :title, class:"form-control" %>
  </div></div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <div> <%= f.text_area :body, class:"form-control", rows:"3" %></div>
  </div>
  <div class="form-group">
   <%= f.submit "Update Book", class:"btn btn-success" %>
  </div>
</form>
<% end %>

<div>
    <%= link_to "Show", book_path(@book.id) %> |
     <%= link_to "Back", books_path %>

</div>

</main>

Bookers2/app/views/books/index.html.erb
<main>

      <% if @book.errors.any? %>
  <div id= "error_explanation" >
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(63,63) %>

      <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
 <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
 <% end %>

</div>


      <h2 class="mt-3">New book</h2>

      <%= form_with model: @book do |f| %>


      <div class="form-group">
        Title
        <%= f.text_field :title, class:"form-control" %>
        </div>
       <div class="form-group">
         Opinion
         <%= f.text_area :body, class:"form-control", rows:"3" %>
         </div>
  <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
        </div>
        </div>

  <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
        <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(40,40) %>
        <% end %>

        </td>
        <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
            </td>


        <td><%= book.body %></td>

           <td>  <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %></td>

  <td><%= link_to " コメント数:#{book.book_comments.count}", book_path(book.id) %></td>

      </tr>
<% end %>


  </tbody>


</table>
    </div>


  </div>
</div>


</main>

Bookers2/app/views/books/new.html.erb
new

Bookers2/app/views/books/show.html.erb
<main>
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @book.user.get_profile_image(63,63) %>

      <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @book.user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @book.user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">

 <%= link_to edit_user_path(@book.user.id), class: "btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
 <% end %>

</div>


      <h2 class="mt-3">New book</h2>

      <%= form_with model: Book.new do |f| %>
      <div class="form-group">
        Title
        <%= f.text_field :title, class:"form-control" %>
        </div>
       <div class="form-group">
         Opinion
         <%= f.text_area :body, class:"form-control", rows:"3" %>
         </div>
  <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
        </div>
        </div>

  <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
  <tbody>
    <tr>
        <td> <%= link_to user_path(@book.user.id) do %>
        <%= image_tag @book.user.get_profile_image(40,40) %>
        <br><%= @book.user.name %>
        <% end %>
        </td>
        <td><%= link_to book_path do %>
              <%= @book.title %>
            <% end %>
            </td>


        <td><%= @book.body %></td>

      <td>  <% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
  <% end %></td>
   <td><%= link_to " コメント数:#{@book.book_comments.count}", book_path(@book) %></td>

        <td> <% if @book.user == current_user %>
    <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>


    <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消去しますか？",  class:"btn btn-sm btn-danger"  %>

  <% end %>
  </td>

    </tr>


  </tbody>



</table>
 <div>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(40,40) %>
    <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
    <%= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment),method: :delete, class:"btn btn-sm btn-danger" %>
    <% end %>
    </p>
    <%= link_to book_comment.user.name, user_path(book_comment.user.id)  %>

  <% end %><br>

   <% if @book_comment.errors.any? %>
  <div id= "error_explanation" >
    <h3><%= @book_comment.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
    <% @book_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %><br>
    <%= f.submit "送信" %>
  <% end %>
</div>
    </div>



  </div>
</div>


</main>

Bookers2/app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

Bookers2/app/views/homes/top.html.erb
      <main>
        <%= flash[:notice] %>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

<body>
    <header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
      <li class="nav-item mr-3">
        <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>

      <li class="nav-item mr-3">
        <%= link_to  users_path, class:" nav-link text-light" do %>
        <i class= "fas fa-users"></i>Users
        <% end %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to books_path, class: "nav-link text-light" do %>
        <i class="fas fa-book-open"></i>Books
        <% end %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class="fas fa-sign-out-alt"></i>logout
        <% end %>
      </li>
    <% else %>

      <li class="nav-item mr-3">
        <%= link_to root_path, class: "nav-link text-light" do %>
        <i class="fas fa-home"></i>Home
        <% end %>
        </li>
      <li class="nav-item mr-3">
        <%= link_to about_path, class: "nav-link text-light" do %>
        <i class="fas fa-link
        "></i>About
        <% end %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>sign up
        <% end %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to new_user_session_path, class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>login
        <% end %>
      </li>

    <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>





<main class ='mb-auto'>
  <%= yield %>
</main>

  <footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

</body>

</html>

Bookers2/app/views/users/edit.html.erb
<main>
    <% if @user.errors.any? %>
  <div id= "error_explanation" >
    <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

 <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
       <div><%= f.text_field :name,autofocus: true, id:"inputName", placeholder:"名前", class:"form-control" %></div>
      </div>
     <div class="form-group">
        <label for="user_image">Image</label>
        <div><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></div>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <div><%= f.text_field :introduction,autofocus: true, id:"inputIntroduction", class:"form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>



         </div>
         <% end %>
     </form>
     </div>
</div>

      </div>
      <

Bookers2/app/views/users/index.html.erb
<main>

    <div class="container px-5 px-sm-0">
        
        <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(63,63) %>

      <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
 <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
 <% end %>



</div>


      <h2 class="mt-3">New book</h2>

      <%= form_with model: @book do |f| %>
      <div class="form-group">
        Title
        <%= f.text_field :title, class:"form-control" %>
        </div>
       <div class="form-group">
         Opinion
         <%= f.text_area :body, class:"form-control", rows:"3" %>
         </div>
  <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
        </div>
        </div>

        <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(40,40) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
<% end %>

  </tbody>
</table>

    </div>
  </div>
</div>





</main>

Bookers2/app/views/users/show.html.erb
<main>
    <%= flash[:notice] %>
        <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(63,63) %>

      <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">


 <%= link_to edit_user_path, class: "btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
<% end %>


</div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model: @book do |f| %>

      <div class="form-group">
          Title
        <%= f.text_field :title, class:"form-control" %>
        </div>
       <div class="form-group">
           Opinion
         <%= f.text_area :body, class:"form-control", rows:"3" %>
         </div>
  <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
        </div>
        </div>










   <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(40,40) %>
          <% end %>
          </td>

        <td><%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
        </td>
        <td><%= book.body %></td>
        <td>  <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %></td>

         <td><%= link_to "コメント数:#{book.book_comments.count} ", book_path(book.id) %></td>
      </tr>

  </tbody>
  <% end %>
</table>
    </div>


  </div>
</div>


</main>